using System.Collections.Generic;

public static class PeriodicElementInitializer { 
    // Get a list of elements and produce the Periodic Table
    public static List<PeriodicElement> GetPeriodicTableElements (List<Element> elements)
    {
        return new List<PeriodicElement>
        {
            new PeriodicElement { Element = elements[0], Row = 0, Column = 0 },
            new PeriodicElement { Element = elements[1], Row = 0, Column = 17 },
            new PeriodicElement { Element = elements[2], Row = 1, Column = 0 },
            new PeriodicElement { Element = elements[3], Row = 1, Column = 1 },
            new PeriodicElement { Element = elements[4], Row = 1, Column = 12 },
            new PeriodicElement { Element = elements[5], Row = 1, Column = 13 },
            new PeriodicElement { Element = elements[6], Row = 1, Column = 14 },
            new PeriodicElement { Element = elements[7], Row = 1, Column = 15 },
            new PeriodicElement { Element = elements[8], Row = 1, Column = 16 },
            new PeriodicElement { Element = elements[9], Row = 1, Column = 17 },
            new PeriodicElement { Element = elements[10], Row = 2, Column = 0 },
            new PeriodicElement { Element = elements[11], Row = 2, Column = 1 },
            new PeriodicElement { Element = elements[12], Row = 2, Column = 12 },
            new PeriodicElement { Element = elements[13], Row = 2, Column = 13 },
            new PeriodicElement { Element = elements[14], Row = 2, Column = 14 },
            new PeriodicElement { Element = elements[15], Row = 2, Column = 15 },
            new PeriodicElement { Element = elements[16], Row = 2, Column = 16 },
            new PeriodicElement { Element = elements[17], Row = 2, Column = 17 },
            new PeriodicElement { Element = elements[18], Row = 3, Column = 0 },
            new PeriodicElement { Element = elements[19], Row = 3, Column = 1 },
            new PeriodicElement { Element = elements[20], Row = 3, Column = 2 },
            new PeriodicElement { Element = elements[21], Row = 3, Column = 3 },
            new PeriodicElement { Element = elements[22], Row = 3, Column = 4 },
            new PeriodicElement { Element = elements[23], Row = 3, Column = 5 },
            new PeriodicElement { Element = elements[24], Row = 3, Column = 6 },
            new PeriodicElement { Element = elements[25], Row = 3, Column = 7 },
            new PeriodicElement { Element = elements[26], Row = 3, Column = 8 },
            new PeriodicElement { Element = elements[27], Row = 3, Column = 9 },
            new PeriodicElement { Element = elements[28], Row = 3, Column = 10 },
            new PeriodicElement { Element = elements[29], Row = 3, Column = 11 },
            new PeriodicElement { Element = elements[30], Row = 3, Column = 12 },
            new PeriodicElement { Element = elements[31], Row = 3, Column = 13 },
            new PeriodicElement { Element = elements[32], Row = 3, Column = 14 },
            new PeriodicElement { Element = elements[33], Row = 3, Column = 15 },
            new PeriodicElement { Element = elements[34], Row = 3, Column = 16 },
            new PeriodicElement { Element = elements[35], Row = 3, Column = 17 },
            new PeriodicElement { Element = elements[36], Row = 4, Column = 0 },
            new PeriodicElement { Element = elements[37], Row = 4, Column = 1 },
            new PeriodicElement { Element = elements[38], Row = 4, Column = 2 },
            new PeriodicElement { Element = elements[39], Row = 4, Column = 3 },
            new PeriodicElement { Element = elements[40], Row = 4, Column = 4 },
            new PeriodicElement { Element = elements[41], Row = 4, Column = 5 },
            new PeriodicElement { Element = elements[42], Row = 4, Column = 6 },
            new PeriodicElement { Element = elements[43], Row = 4, Column = 7 },
            new PeriodicElement { Element = elements[44], Row = 4, Column = 8 },
            new PeriodicElement { Element = elements[45], Row = 4, Column = 9 },
            new PeriodicElement { Element = elements[46], Row = 4, Column = 10 },
            new PeriodicElement { Element = elements[47], Row = 4, Column = 11 },
            new PeriodicElement { Element = elements[48], Row = 4, Column = 12 },
            new PeriodicElement { Element = elements[49], Row = 4, Column = 13 },
            new PeriodicElement { Element = elements[50], Row = 4, Column = 14 },
            new PeriodicElement { Element = elements[51], Row = 4, Column = 15 },
            new PeriodicElement { Element = elements[52], Row = 4, Column = 16 },
            new PeriodicElement { Element = elements[53], Row = 4, Column = 17 },
            new PeriodicElement { Element = elements[54], Row = 5, Column = 0},
            new PeriodicElement { Element = elements[55], Row = 5, Column = 1},
            new PeriodicElement { Element = elements[71], Row = 5, Column = 3},
            new PeriodicElement { Element = elements[72], Row = 5, Column = 4},
            new PeriodicElement { Element = elements[73], Row = 5, Column = 5},
            new PeriodicElement { Element = elements[74], Row = 5, Column = 6},
            new PeriodicElement { Element = elements[75], Row = 5, Column = 7},
            new PeriodicElement { Element = elements[76], Row = 5, Column = 8},
            new PeriodicElement { Element = elements[77], Row = 5, Column = 9},
            new PeriodicElement { Element = elements[78], Row = 5, Column = 10},
            new PeriodicElement { Element = elements[79], Row = 5, Column = 11},
            new PeriodicElement { Element = elements[80], Row = 5, Column = 12},
            new PeriodicElement { Element = elements[81], Row = 5, Column = 13},
            new PeriodicElement { Element = elements[82], Row = 5, Column = 14},
            new PeriodicElement { Element = elements[83], Row = 5, Column = 15},
            new PeriodicElement { Element = elements[84], Row = 5, Column = 16},
            new PeriodicElement { Element = elements[85], Row = 5, Column = 17},
            new PeriodicElement { Element = elements[86], Row = 6, Column = 0},
            new PeriodicElement { Element = elements[87], Row = 6, Column = 1},
            new PeriodicElement { Element = elements[103], Row = 6, Column = 3},
            new PeriodicElement { Element = elements[104], Row = 6, Column = 4},
            new PeriodicElement { Element = elements[105], Row = 6, Column = 5},
            new PeriodicElement { Element = elements[106], Row = 6, Column = 6},
            new PeriodicElement { Element = elements[107], Row = 6, Column = 7},
            new PeriodicElement { Element = elements[108], Row = 6, Column = 8},
            new PeriodicElement { Element = elements[109], Row = 6, Column = 9},
            new PeriodicElement { Element = elements[110], Row = 6, Column = 10},
            new PeriodicElement { Element = elements[111], Row = 6, Column = 11},
            new PeriodicElement { Element = elements[112], Row = 6, Column = 12},
            new PeriodicElement { Element = elements[113], Row = 6, Column = 13},
            new PeriodicElement { Element = elements[114], Row = 6, Column = 14},
            new PeriodicElement { Element = elements[115], Row = 6, Column = 15},
            new PeriodicElement { Element = elements[116], Row = 6, Column = 16},
            new PeriodicElement { Element = elements[117], Row = 6, Column = 17},

            // F Block
            new PeriodicElement { Element = elements[56], Row = 8, Column = 3},
            new PeriodicElement { Element = elements[57], Row = 8, Column = 4},
            new PeriodicElement { Element = elements[58], Row = 8, Column = 5},
            new PeriodicElement { Element = elements[59], Row = 8, Column = 6},
            new PeriodicElement { Element = elements[60], Row = 8, Column = 7},
            new PeriodicElement { Element = elements[61], Row = 8, Column = 8},
            new PeriodicElement { Element = elements[62], Row = 8, Column = 9},
            new PeriodicElement { Element = elements[63], Row = 8, Column = 10},
            new PeriodicElement { Element = elements[64], Row = 8, Column = 11},
            new PeriodicElement { Element = elements[65], Row = 8, Column = 12},
            new PeriodicElement { Element = elements[66], Row = 8, Column = 13},
            new PeriodicElement { Element = elements[67], Row = 8, Column = 14},
            new PeriodicElement { Element = elements[68], Row = 8, Column = 15},
            new PeriodicElement { Element = elements[69], Row = 8, Column = 16},
            new PeriodicElement { Element = elements[70], Row = 8, Column = 17},
            new PeriodicElement { Element = elements[88], Row = 9, Column = 3},
            new PeriodicElement { Element = elements[89], Row = 9, Column = 4},
            new PeriodicElement { Element = elements[90], Row = 9, Column = 5},
            new PeriodicElement { Element = elements[91], Row = 9, Column = 6},
            new PeriodicElement { Element = elements[92], Row = 9, Column = 7},
            new PeriodicElement { Element = elements[93], Row = 9, Column = 8},
            new PeriodicElement { Element = elements[94], Row = 9, Column = 9},
            new PeriodicElement { Element = elements[95], Row = 9, Column = 10},
            new PeriodicElement { Element = elements[96], Row = 9, Column = 11},
            new PeriodicElement { Element = elements[97], Row = 9, Column = 12},
            new PeriodicElement { Element = elements[98], Row = 9, Column = 13},
            new PeriodicElement { Element = elements[99], Row = 9, Column = 14},
            new PeriodicElement { Element = elements[100], Row = 9, Column = 15},
            new PeriodicElement { Element = elements[101], Row = 9, Column = 16},
            new PeriodicElement { Element = elements[102], Row = 9, Column = 17},
        };
    }
}